# Generated by Django 5.0.6 on 2024-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cryptotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images/'),
        ),
    ]
