# Generated by Django 5.0.6 on 2024-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cryptotransaction_transaction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotransaction',
            name='amount_naira',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='cryptocurrency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='transaction_image',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/'),
        ),
    ]
